---
- name: Ensure standard dirs exist
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
  with_items:
    - ~/vc
    - ~/bin
    - ~/.config/kak
    - ~/.config/kak-lsp
    - ~/.config/fish
    - ~/.local/bin
  tags: symlink

- name: Ensure ssh dir exists
  ansible.builtin.file:
    path: ~/.ssh
    state: directory
    mode: "0700"
  tags: symlink


- name: Symlink files
  file: path={{ item.path }} src=~/vc/workstation-setup/roles/dotfiles-deprecated/files/{{ item.src }} state=link
  tags: symlink
  with_items:
    - src: kakrc
      path: ~/.config/kak/kakrc
    - src: tigrc
      path: ~/.tigrc
    - src: gitconfig
      path: ~/.gitconfig
    - src: kak-lsp.toml
      path: ~/.config/kak-lsp/kak-lsp.toml
    - src: extract-jira-ticket.sh
      path: ~/bin/extract-jira-ticket.sh
    - src: nnn-for-kak.sh
      path: ~/bin/nnn-for-kak.sh
    - src: nnn-kak-opener.sh
      path: ~/bin/nnn-kak-opener.sh
    - src: prepare-commit-msg-with-jira-ticket.sh
      path: ~/bin/prepare-commit-msg-with-jira-ticket.sh
    - src: jenkins-build-with-param.js
      path: ~/bin/jenkins-build-with-param.js
    - src: edit-file-in-kak-session.sh
      path: ~/bin/edit-file-in-kak-session.sh

- name: Install ssh config
  template:
    src: ssh_config.j2
    dest: ~/.ssh/config
