---
- name: Ensure standard dirs exist
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
  with_items:
    - ~/vc
    # This is necessary so Stow doesn't turn autoload into a symlink
    # We need to do some symlinking inside of autoload during the kakoune
    # role, so we only want Stow to make changes inside of it.  See dotfiles
    # role for stow usage
    - ~/.config/kak/autoload

- name: Ensure ssh dir exists
  ansible.builtin.file:
    path: ~/.ssh
    state: directory
    mode: "0700"
