---
- name: Install packages
  ansible.builtin.package:
    name:
      - vlc
      - audacity
    state: present
  become: true

# - name: Install AUR packages
#   kewlfft.aur.aur:
#     name:
#       - slack-desktop
#       - playwright
#   when: ansible_facts['os_family'] == 'Archlinux'
